### ISSUE TITLE
collaborative text editor: null

### ISSUE THREAD

**Issue by michaelvoronov** [brynbellomy/redwood#26]
Hi!

I am trying to start the collaborative text editor on MacOS with go 1.13 and it produces a page contains only "null" string:

<img width="494" alt="Screen Shot 2019-12-09 at 20 56 00" src="https://user-images.githubusercontent.com/11981714/70459970-5c250c00-1ac6-11ea-874e-afccccb2b3bc.png">

The node log contains following records:

```
2019/12/09 20:45:43 http: TLS handshake error from [::1]:56395: remote error: tls: unknown certificate
2019/12/09 20:45:43 http: TLS handshake error from [::1]:56396: remote error: tls: unknown certificate
2019/12/09 20:45:44 http: TLS handshake error from [::1]:56397: remote error: tls: unknown certificate
2019/12/09 20:45:44 http: TLS handshake error from [::1]:56398: remote error: tls: unknown certificate
E1209 20:45:44.839110        transport.http.go:0788] [bd2eeb transport] error reading signed sessionid cookie: cookie 'sessionid' has invalid signature (value: 78477f44646c058f226a5452ae8a8c6787722def42bc60094e73efd4d8696920): bad cookie
I1209 20:45:48.193904      transport.libp2p.go:0474] [962168 transport] announce
E1209 20:45:48.203055        transport.http.go:0788] [962168 transport] error reading signed sessionid cookie: cookie 'sessionid' has invalid signature (value: 62995696e6975a8f7dc99625da77d9a215447c70f8c3f2b2c8706206d31a4f33): bad cookie
```

Tried to recreate certs with `make-certs.sh`.

**Comment by brynbellomy** [comment]
I've just pushed a new commit, and I've taken some time to guarantee that the demos are all working correctly (at least for me).  I'd be grateful if you would pull the latest changes and try again.  A couple of pointers:

1. After you pull, you'll need to use a slightly different URL: https://localhost:21232/chat/talk0/index.html
2. It looks like you have two browser tabs open, right?  One of them will need to be in a private browser window, and the other one in a regular browser window.  Otherwise, the `sessionid` cookie will be overwritten over and over again as each tab makes requests.
3. The TLS errors you included are expected -- they shouldn't affect the demo.  Turns out Golang doesn't trust self-signed certs by default :)
